name: Generate Snake

on:
  schedule: # executa automaticamente todo dia
    - cron: "0 0 * * *"
  workflow_dispatch: # permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Gera o gráfico da cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: Cadu-f12 
          outputs: dist/github-contribution-grid-snake.svg

      - name: Publica no branch de saída
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

